# fly.toml app configuration file generated for pseura-test on 2024-05-31T10:49:45+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pseura-test'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
